apiVersion: v1
appVersion: 0.0.1
description: |
  Upbound Universal Crossplane (UXP) is Upbound's official enterprise-grade
  distribution of Crossplane. It's fully compatible with upstream Crossplane,
  open source, capable of connecting to Upbound Cloud for real-time dashboard
  visibility, and maintained by Upbound. It's the easiest way for both
  individual community members and enterprises to build their production control
  planes.
name: universal-crossplane
version: 0.0.1
icon: https://crossplane.io/images/favicon_192x192.png
home: https://upbound.io
maintainers:
  - name: Upbound Inc.
    email: info@upbound.io
keywords:
  - cloud
  - infrastructure
  - services
  - application
  - database
  - cache
  - bucket
  - infra
  - app
  - ops
  - oam
  - gcp
  - azure
  - aws
  - alibaba
  - cloudsql
  - rds
  - s3
  - azuredatabase
  - asparadb
  - gke
  - aks
  - eks
