apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: getting-started-with-aws
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/universal-crossplane
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      An introductory example to UXP and Composition for AWS.
    meta.crossplane.io/readme: |
      An introductory example to UXP and Composition for AWS.
      This will enable provisioning of an RDS database instance.

      [Quickstart](https://docs.upbound.io/quickstart/community-providers/)
    uxp-guide: getting-started
spec:
  crossplane:
    version: ">=v1.2.1-0"
  dependsOn:
    - provider: registry.upbound.io/crossplane/provider-aws
      version: ">=v0.22.0-0"
