// Copyright 2021 Upbound Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/upbound/universal-crossplane/internal/clients/upbound (interfaces: Client)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	upbound "github.com/upbound/universal-crossplane/internal/clients/upbound"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// FetchNewJWTToken mocks base method.
func (m *MockClient) FetchNewJWTToken(arg0, arg1, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchNewJWTToken", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchNewJWTToken indicates an expected call of FetchNewJWTToken.
func (mr *MockClientMockRecorder) FetchNewJWTToken(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchNewJWTToken", reflect.TypeOf((*MockClient)(nil).FetchNewJWTToken), arg0, arg1, arg2)
}

// GetAgentCerts mocks base method.
func (m *MockClient) GetAgentCerts(arg0 string) (upbound.PublicCerts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentCerts", arg0)
	ret0, _ := ret[0].(upbound.PublicCerts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentCerts indicates an expected call of GetAgentCerts.
func (mr *MockClientMockRecorder) GetAgentCerts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentCerts", reflect.TypeOf((*MockClient)(nil).GetAgentCerts), arg0)
}
